### ISSUE TITLE
Sending Gram's error - check your wallet's balance

### ISSUE THREAD

**Issue by denysord88** [ton-blockchain/wallet-desktop#18]
My wallet - EQBWF6nixDUSSiGzi3KdzLH7M-7B9H8-t0eVSw-9d9CMS1u9

Error:
Sending failed
Could not perform the transaction. Please check your wallet's balance and try again.

Wallet version - 0.9.3
Ubuntu - 16.04 LTS
Time - 2019-11-05 22:30
Balance 18,001238995
Amount 2
Comment - test

**Comment by john-preston** [comment]
Did it happen once or you can reproduce it more times?

**Comment by denysord88** [comment]
@john-preston it happened once. I can't reproduce it now.

**Comment by john-preston** [comment]
If there will be a way to reproduce the error I'll try to debug it.
