### ISSUE TITLE
Don't receive my test Grams from @test_ton_bot (Telegram)

### ISSUE THREAD

**Issue by darafshi** [ton-blockchain/wallet-desktop#22]
M M, [۰۸.۱۱.۱۹ ۲۰:۲۶]
/start

TestTonBot, [۰۸.۱۱.۱۹ ۲۰:۲۶]
Hello! Please send me your wallet address to get test grams.

M M, [۰۹.۱۱.۱۹ ۰۸:۴۱]
EQA4DpdyhxR2Hm03FMWud95bJLm7x9v0-LP9XCjZ28qPG0OK

TestTonBot, [۰۹.۱۱.۱۹ ۰۸:۴۱]
Enter the amount of test grams you want to get (5 – 20):

M M, [۰۹.۱۱.۱۹ ۰۸:۴۱]
20

TestTonBot, [۰۹.۱۱.۱۹ ۰۸:۴۱]
Please wait while your request is being processed. This can take some time, especially when the demand for test grams is high.

TestTonBot, [۰۹.۱۱.۱۹ ۰۸:۴۱]
Test grams requested. They will be credited to your wallet soon.

Note that this operation may take some time, depending on the current demand for test grams.

**Do you have any idea about this delay?**

**Comment by john-preston** [comment]
I have no idea. And I can't do anything about that here.
