### ISSUE TITLE
Feature Request: Proxy Settings like Telegram Desktop

### ISSUE THREAD

**Issue by Oblivion94** [ton-blockchain/wallet-desktop#3]
Great idea. I would like to make the proposal to add options to manage proxies. In the version of Telegram Desktop it comes by default and for many it is very necessary. Regards!

**Comment by RadRussianRus** [comment]
Is there a need in that? It works fine for me without proxy.

**Comment by john-preston** [comment]
I don't think this is relevant, especially right now, on the testnet.

**Comment by Oblivion94** [comment]
Thanks for answering. Let's have people who have the internet provided by an institution that uses proxy. Thanks to the configuration of Telegram Desktop we can access from Linux. My request is addressed to all those people who work behind an institutional proxy.
