### ISSUE TITLE
Internal Server Error (500) in the console, when sending funds with incorrect data specified in device settings

### ISSUE THREAD

**Issue by julialips** [ton-blockchain/wallet-desktop#38]
### Bug Type

Functional

### Reproduction steps

Preconditions: 
1. Open 'Data and time' settings and set a day before from current date. 
2. You have positive TON balance in your TON wallet.

Steps: 
1. Open the site https://wallet.ton.org/ and log in to your account
2. Click 'Receive' button
3. Click 'Share Wallet Address' and close the pop-up
4. Click 'Send' button
5. Enter TON address, from step 3, into the 'Recipient wallet address' field
6. Enter a valid TON amount
7. Click the 'Send TON' button
8. Confirm send transaction at the 'Confirmation pop-up'
9. Enter valid password and click 'Next' button

### Actual result

"API request error" appears, 500 error in the console.
So, impossible to send funds, no info about the error. 
<img width="930" alt="12" src="https://user-images.githubusercontent.com/45575431/190866753-20faef41-683c-4e0a-8825-50385953cbaa.png">

### Expected result

Depends of your data logic already implemented. 
But the error should be fixed and handled. 

### Suggested Severity

Critical

### Device

    OS: Windows
    Browser: Opera
    Version: 90.0.4480.54

**Comment by EmelyanenkoK** [comment]
Wrong repo

**Comment by julialips** [comment]
> Wrong repo. This issue will be accounted as if it was posted in https://github.com/toncenter/ton-wallet/issues

Thank you. Should I duplicate issues in the right repository?

**Comment by EmelyanenkoK** [comment]
> Thank you. Should I duplicate issues in the right repository?
Yes, please duplicate it and add link to original issue, to be sure that it won't be forgotten.
