### ISSUE TITLE
Incorrect window position in multi-display configuration

### ISSUE THREAD

**Issue by NetLagina** [ton-blockchain/wallet-desktop#8]
Windows 7 Ultimate
In a two-display configuration,
![image](https://user-images.githubusercontent.com/14164722/68083785-bda5eb00-fe35-11e9-8cf5-72c02bc1432c.png)
the wallet window opens at the border of two displays
![dasdasd](https://user-images.githubusercontent.com/14164722/68083839-70764900-fe36-11e9-9b0a-59bd014b298f.png)

**Comment by afansv** [comment]
why closed?
